import {
  Job, CandidateProfile, EmployerProfile, Application,
  Conversation, Notification, User,
} from "./types";

export const mockUsers: User[] = [
  { id: "u1", name: "Lucas Ferreira", email: "lucas@email.com", role: "candidate", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas", createdAt: "2026-01-10" },
  { id: "u2", name: "Fernanda Costa", email: "fernanda@pousada.com", role: "employer", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fernanda", createdAt: "2026-01-05" },
  { id: "u3", name: "Ricardo Santos", email: "ricardo@email.com", role: "candidate", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ricardo", createdAt: "2026-02-01" },
  { id: "u4", name: "Ana Lima", email: "ana@email.com", role: "candidate", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ana", createdAt: "2026-02-15" },
];

export const mockCandidateProfiles: CandidateProfile[] = [
  {
    userId: "u1",
    bio: "Apaixonado por turismo e hospitalidade. Busco minha primeira experiência no setor em Ubatuba.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas",
    experiences: [
      { id: "e1", role: "Atendente", company: "Supermercado Centro", startDate: "2024-06", endDate: "2025-12", current: false, description: "Atendimento ao cliente, caixa e reposição." }
    ],
    education: [
      { id: "ed1", institution: "ETEC Ubatuba", course: "Técnico em Turismo", level: "Técnico", startDate: "2023-02", endDate: "2025-11", current: false }
    ],
    skills: [
      { name: "Atendimento ao cliente", level: "Avançado", validated: true },
      { name: "Espanhol", level: "Intermediário" },
      { name: "Pacote Office", level: "Básico" },
    ],
    languages: [{ name: "Português", level: "Nativo" }, { name: "Inglês", level: "Básico" }],
    salaryMin: 1800,
    salaryMax: 2500,
    salaryVisible: true,
    availability: "Imediata",
    desiredContracts: ["CLT", "Temporário"],
    portfolio: [],
    profileCompleteness: 78,
    city: "Ubatuba",
    state: "SP",
  },
  {
    userId: "u3",
    bio: "Profissional de administração com 15 anos de experiência. Em recolocação após mudança para Ubatuba.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ricardo",
    experiences: [
      { id: "e2", role: "Gerente Administrativo", company: "Construtora ABC", startDate: "2018-03", endDate: "2025-10", current: false, description: "Gestão de equipe de 20 pessoas, controles financeiros e operacionais." },
      { id: "e3", role: "Analista Financeiro", company: "Banco XYZ", startDate: "2010-01", endDate: "2018-02", current: false, description: "Análise de crédito e gestão de carteiras." },
    ],
    education: [
      { id: "ed2", institution: "Universidade Paulista", course: "Administração de Empresas", level: "Graduação", startDate: "2006-02", endDate: "2010-11", current: false }
    ],
    skills: [
      { name: "Gestão de equipes", level: "Avançado", validated: true },
      { name: "Excel Avançado", level: "Avançado", validated: true },
      { name: "Power BI", level: "Intermediário" },
      { name: "Gestão financeira", level: "Avançado" },
    ],
    languages: [{ name: "Português", level: "Nativo" }, { name: "Inglês", level: "Intermediário" }, { name: "Espanhol", level: "Básico" }],
    salaryMin: 5000,
    salaryMax: 8000,
    salaryVisible: false,
    availability: "Imediata",
    desiredContracts: ["CLT", "PJ"],
    portfolio: [{ title: "Projeto de reestruturação financeira", url: "#", type: "link" }],
    profileCompleteness: 92,
    city: "Ubatuba",
    state: "SP",
  },
];

export const mockEmployerProfiles: EmployerProfile[] = [
  {
    userId: "u2",
    companyName: "Pousada Mar Azul",
    logo: "https://api.dicebear.com/7.x/shapes/svg?seed=pousada",
    description: "Pousada boutique à beira-mar com 20 apartamentos. Ambiente familiar e aconchegante no coração de Ubatuba.",
    sector: "Hospitalidade",
    size: "Micro",
    city: "Ubatuba",
    state: "SP",
    website: "https://pousadamarazul.com.br",
    benefits: ["Refeição no local", "Vale transporte", "Uniforme fornecido", "Comissão por avaliação"],
    rating: 4.7,
    reviewCount: 23,
    activeJobs: 3,
  },
  {
    userId: "emp2",
    companyName: "Restaurante Maré Alta",
    logo: "https://api.dicebear.com/7.x/shapes/svg?seed=restaurante",
    description: "Restaurante especializado em frutos do mar há 15 anos em Ubatuba.",
    sector: "Gastronomia",
    size: "Pequena",
    city: "Ubatuba",
    state: "SP",
    benefits: ["Alimentação no local", "Vale transporte", "Gorjeta dividida"],
    rating: 4.3,
    reviewCount: 41,
    activeJobs: 2,
  },
  {
    userId: "emp3",
    companyName: "Surf School Ubatuba",
    logo: "https://api.dicebear.com/7.x/shapes/svg?seed=surf",
    description: "Escola de surf e esportes aquáticos. Principal escola da região há 10 anos.",
    sector: "Esportes & Lazer",
    size: "Micro",
    city: "Ubatuba",
    state: "SP",
    benefits: ["Aulas de surf gratuitas", "Uniforme", "Ambiente jovem"],
    rating: 4.9,
    reviewCount: 18,
    activeJobs: 1,
  },
];

export const mockJobs: Job[] = [
  {
    id: "j1",
    employerId: "u2",
    employerName: "Pousada Mar Azul",
    employerLogo: "https://api.dicebear.com/7.x/shapes/svg?seed=pousada",
    title: "Recepcionista de Pousada",
    description: `## Sobre a vaga\n\nBuscamos recepcionista com perfil acolhedor para compor nossa equipe na temporada de verão.\n\n## Responsabilidades\n\n- Check-in e check-out de hóspedes\n- Atendimento telefônico e por WhatsApp\n- Controle de reservas no sistema\n- Auxílio aos hóspedes com informações turísticas sobre Ubatuba\n\n## Requisitos\n\n- Ensino médio completo\n- Boa comunicação verbal e escrita\n- Noções básicas de inglês (desejável)\n- Disponibilidade para trabalho nos fins de semana`,
    category: "Turismo",
    subcategory: "Recepção",
    contractType: "Temporário",
    regime: "Presencial",
    salaryMin: 1800,
    salaryMax: 2200,
    salaryPeriod: "mês",
    experience: "Júnior",
    city: "Ubatuba",
    state: "SP",
    seasonal: true,
    seasonStart: "Dezembro",
    seasonEnd: "Fevereiro",
    featured: true,
    deadline: "2026-05-15",
    publishedAt: "2026-04-01",
    applications: 12,
    maxApplications: 50,
    questions: [
      { id: "q1", text: "Você tem disponibilidade para trabalhar nos finais de semana?", required: true },
      { id: "q2", text: "Possui experiência com algum sistema de reservas (ex: Booking, Airbnb)?", required: false },
    ],
    benefits: ["Refeição no local", "Vale transporte", "Uniforme fornecido"],
    matchScore: 87,
    saved: false,
  },
  {
    id: "j2",
    employerId: "emp2",
    employerName: "Restaurante Maré Alta",
    employerLogo: "https://api.dicebear.com/7.x/shapes/svg?seed=restaurante",
    title: "Garçom / Garçonete",
    description: `## Descrição\n\nRestaurante de frutos do mar busca garçom/garçonete para atendimento em alto padrão.\n\n## O que você vai fazer\n\n- Atendimento às mesas com excelência\n- Apresentação do cardápio e sugestões ao cliente\n- Suporte na organização do salão\n\n## Perfil desejado\n\n- Experiência prévia em restaurante (preferencial)\n- Boa apresentação pessoal\n- Inglês básico para atendimento a turistas estrangeiros`,
    category: "Gastronomia",
    subcategory: "Atendimento",
    contractType: "CLT",
    regime: "Presencial",
    salaryMin: 1600,
    salaryMax: 2000,
    salaryPeriod: "mês",
    experience: "Sem experiência",
    city: "Ubatuba",
    state: "SP",
    seasonal: false,
    featured: false,
    deadline: "2026-05-30",
    publishedAt: "2026-04-05",
    applications: 8,
    questions: [],
    benefits: ["Alimentação no local", "Vale transporte", "Gorjeta dividida"],
    matchScore: 65,
    saved: true,
  },
  {
    id: "j3",
    employerId: "emp3",
    employerName: "Surf School Ubatuba",
    employerLogo: "https://api.dicebear.com/7.x/shapes/svg?seed=surf",
    title: "Instrutor de Surf",
    description: `## Vaga para instrutor de surf\n\nBuscamos instrutor apaixonado pelo esporte para dar aulas para iniciantes e intermediários.\n\n## Requisitos\n\n- Certificação BASA ou similar\n- Experiência mínima de 2 anos como instrutor\n- Inglês intermediário (turistas internacionais)\n- Curso de primeiros socorros\n\n## Diferenciais\n\n- Outras modalidades: stand-up paddle, bodyboard`,
    category: "Esportes & Lazer",
    subcategory: "Instrução Esportiva",
    contractType: "PJ",
    regime: "Presencial",
    salaryMin: 3000,
    salaryMax: 5000,
    salaryPeriod: "mês",
    experience: "Pleno",
    city: "Ubatuba",
    state: "SP",
    seasonal: true,
    seasonStart: "Outubro",
    seasonEnd: "Março",
    featured: false,
    deadline: "2026-06-01",
    publishedAt: "2026-04-08",
    applications: 5,
    questions: [
      { id: "q3", text: "Qual sua certificação de surf?", required: true },
    ],
    benefits: ["Aulas de surf gratuitas", "Uniforme", "Ambiente jovem"],
    matchScore: 72,
    saved: false,
  },
  {
    id: "j4",
    employerId: "u2",
    employerName: "Pousada Mar Azul",
    employerLogo: "https://api.dicebear.com/7.x/shapes/svg?seed=pousada",
    title: "Auxiliar de Limpeza e Camareira",
    description: `## Vaga para camareira\n\nAuxiliar de limpeza e camareira para pousada boutique.\n\n## Atividades\n\n- Limpeza e organização dos apartamentos\n- Troca de roupas de cama e banho\n- Reposição de itens de amenidades\n- Relatório de manutenção\n\n## Perfil\n\n- Atenção aos detalhes\n- Organização\n- Experiência em hotelaria (diferencial)`,
    category: "Hospitalidade",
    subcategory: "Limpeza e Conservação",
    contractType: "CLT",
    regime: "Presencial",
    salaryMin: 1412,
    salaryMax: 1600,
    salaryPeriod: "mês",
    experience: "Sem experiência",
    city: "Ubatuba",
    state: "SP",
    seasonal: false,
    featured: false,
    deadline: "2026-05-20",
    publishedAt: "2026-04-10",
    applications: 18,
    questions: [],
    benefits: ["Refeição no local", "Vale transporte", "Uniforme"],
    matchScore: 45,
    saved: false,
  },
  {
    id: "j5",
    employerId: "emp4",
    employerName: "Clínica Saúde & Mar",
    employerLogo: "https://api.dicebear.com/7.x/shapes/svg?seed=clinica",
    title: "Recepcionista de Clínica",
    description: `## Sobre a vaga\n\nClínica médica multi-especialidades busca recepcionista para turno matutino.\n\n## Responsabilidades\n\n- Agendamento de consultas\n- Recepção de pacientes\n- Gestão de prontuários digitais\n- Cobrança e convênios\n\n## Requisitos\n\n- Ensino médio completo\n- Experiência em recepção ou atendimento ao cliente\n- Familiaridade com sistemas de agendamento`,
    category: "Saúde",
    subcategory: "Recepção Médica",
    contractType: "CLT",
    regime: "Presencial",
    salaryMin: 1800,
    salaryMax: 2400,
    salaryPeriod: "mês",
    experience: "Júnior",
    city: "Ubatuba",
    state: "SP",
    seasonal: false,
    featured: false,
    deadline: "2026-05-25",
    publishedAt: "2026-04-12",
    applications: 22,
    questions: [],
    benefits: ["Vale refeição", "Plano de saúde", "Vale transporte"],
    matchScore: 78,
    saved: false,
  },
  {
    id: "j6",
    employerId: "emp5",
    employerName: "Imobiliária Litoral Norte",
    employerLogo: "https://api.dicebear.com/7.x/shapes/svg?seed=imob",
    title: "Corretor de Imóveis",
    description: `## Oportunidade para corretores\n\nImobiliária especializada no litoral norte busca corretores autônomos.\n\n## Perfil\n\n- CRECI ativo\n- Experiência em vendas e locações de temporada\n- Carteira de clientes (diferencial)\n\n## O que oferecemos\n\n- Comissão acima do mercado\n- Suporte de marketing\n- Sistema de CRM completo`,
    category: "Imóveis",
    subcategory: "Vendas",
    contractType: "Autônomo",
    regime: "Híbrido",
    salaryMin: 4000,
    salaryMax: 9000,
    salaryPeriod: "mês",
    experience: "Pleno",
    city: "Ubatuba",
    state: "SP",
    seasonal: false,
    featured: true,
    deadline: "2026-06-30",
    publishedAt: "2026-04-15",
    applications: 7,
    questions: [
      { id: "q4", text: "Você possui CRECI ativo?", required: true },
    ],
    benefits: ["Comissão competitiva", "Flexibilidade de horário", "Suporte de marketing"],
    matchScore: 55,
    saved: false,
  },
];

export const mockApplications: Application[] = [
  {
    id: "app1",
    jobId: "j1",
    jobTitle: "Recepcionista de Pousada",
    employerName: "Pousada Mar Azul",
    employerLogo: "https://api.dicebear.com/7.x/shapes/svg?seed=pousada",
    candidateId: "u1",
    candidateName: "Lucas Ferreira",
    candidateAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas",
    status: "Entrevista",
    appliedAt: "2026-04-02",
    updatedAt: "2026-04-10",
    coverLetter: "Tenho muito interesse nesta vaga e acredito que minha experiência em atendimento e meu curso técnico em turismo me tornam um ótimo candidato.",
    matchScore: 87,
  },
  {
    id: "app2",
    jobId: "j5",
    jobTitle: "Recepcionista de Clínica",
    employerName: "Clínica Saúde & Mar",
    employerLogo: "https://api.dicebear.com/7.x/shapes/svg?seed=clinica",
    candidateId: "u1",
    candidateName: "Lucas Ferreira",
    candidateAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas",
    status: "Em análise",
    appliedAt: "2026-04-13",
    updatedAt: "2026-04-13",
    matchScore: 78,
  },
  {
    id: "app3",
    jobId: "j2",
    jobTitle: "Garçom / Garçonete",
    employerName: "Restaurante Maré Alta",
    employerLogo: "https://api.dicebear.com/7.x/shapes/svg?seed=restaurante",
    candidateId: "u1",
    candidateName: "Lucas Ferreira",
    candidateAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas",
    status: "Recusado",
    appliedAt: "2026-04-06",
    updatedAt: "2026-04-08",
    matchScore: 65,
  },
];

export const mockEmployerApplications: Application[] = [
  {
    id: "eapp1",
    jobId: "j1",
    jobTitle: "Recepcionista de Pousada",
    employerName: "Pousada Mar Azul",
    candidateId: "u1",
    candidateName: "Lucas Ferreira",
    candidateAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas",
    status: "Entrevista",
    appliedAt: "2026-04-02",
    updatedAt: "2026-04-10",
    matchScore: 87,
  },
  {
    id: "eapp2",
    jobId: "j1",
    jobTitle: "Recepcionista de Pousada",
    employerName: "Pousada Mar Azul",
    candidateId: "u3",
    candidateName: "Ricardo Santos",
    candidateAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ricardo",
    status: "Em análise",
    appliedAt: "2026-04-03",
    updatedAt: "2026-04-03",
    matchScore: 72,
  },
  {
    id: "eapp3",
    jobId: "j1",
    jobTitle: "Recepcionista de Pousada",
    employerName: "Pousada Mar Azul",
    candidateId: "c5",
    candidateName: "Carla Mendes",
    candidateAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carla",
    status: "Aplicada",
    appliedAt: "2026-04-05",
    updatedAt: "2026-04-05",
    matchScore: 60,
  },
  {
    id: "eapp4",
    jobId: "j1",
    jobTitle: "Recepcionista de Pousada",
    employerName: "Pousada Mar Azul",
    candidateId: "c6",
    candidateName: "Pedro Almeida",
    candidateAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Pedro",
    status: "Aprovado",
    appliedAt: "2026-03-28",
    updatedAt: "2026-04-15",
    matchScore: 93,
  },
];

export const mockConversations: Conversation[] = [
  {
    id: "conv1",
    jobId: "j1",
    jobTitle: "Recepcionista de Pousada",
    candidateId: "u1",
    candidateName: "Lucas Ferreira",
    candidateAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas",
    employerId: "u2",
    employerName: "Pousada Mar Azul",
    employerLogo: "https://api.dicebear.com/7.x/shapes/svg?seed=pousada",
    lastMessage: "Olá Lucas! Gostamos do seu perfil e gostaríamos de agendar uma entrevista.",
    lastMessageAt: "2026-04-10T14:30:00",
    unread: 1,
    messages: [
      { id: "m1", conversationId: "conv1", senderId: "u2", text: "Olá Lucas! Gostamos do seu perfil e gostaríamos de agendar uma entrevista.", sentAt: "2026-04-10T14:30:00", read: false },
      { id: "m2", conversationId: "conv1", senderId: "u1", text: "Olá! Fico muito feliz com o retorno. Tenho disponibilidade na próxima semana.", sentAt: "2026-04-10T15:00:00", read: true },
      { id: "m3", conversationId: "conv1", senderId: "u2", text: "Ótimo! Poderia ser na terça, dia 16 de abril, às 10h?", sentAt: "2026-04-10T15:15:00", read: true },
    ],
  },
];

export const mockNotifications: Notification[] = [
  { id: "n1", type: "application_update", title: "Entrevista agendada!", body: "Pousada Mar Azul quer agendar uma entrevista para Recepcionista.", read: false, createdAt: "2026-04-10T14:30:00", link: "/vagas/j1" },
  { id: "n2", type: "new_job", title: "Nova vaga compatível", body: "Recepcionista de Clínica — 78% de compatibilidade com seu perfil.", read: false, createdAt: "2026-04-12T09:00:00", link: "/vagas/j5" },
  { id: "n3", type: "seasonal", title: "Temporada de inverno se aproxima!", body: "Em 60 dias começa a temporada de inverno. Confira vagas sazonais.", read: true, createdAt: "2026-04-08T08:00:00", link: "/vagas?seasonal=true" },
  { id: "n4", type: "application_update", title: "Candidatura visualizada", body: "Restaurante Maré Alta visualizou sua candidatura.", read: true, createdAt: "2026-04-07T11:00:00" },
];

export const jobCategories = [
  { value: "Turismo", label: "Turismo", subcategories: ["Recepção", "Guia Turístico", "Gerência Hoteleira", "Concierge"] },
  { value: "Gastronomia", label: "Gastronomia", subcategories: ["Atendimento", "Cozinha", "Confeitaria", "Bartender"] },
  { value: "Hospitalidade", label: "Hospitalidade", subcategories: ["Limpeza e Conservação", "Manutenção", "Gerência"] },
  { value: "Esportes & Lazer", label: "Esportes & Lazer", subcategories: ["Instrução Esportiva", "Mergulho", "Trilhas", "Nauticismo"] },
  { value: "Saúde", label: "Saúde", subcategories: ["Recepção Médica", "Fisioterapia", "Enfermagem", "Nutrição"] },
  { value: "Comércio", label: "Comércio", subcategories: ["Vendas", "Estoque", "Caixa", "Gerência"] },
  { value: "Construção", label: "Construção", subcategories: ["Pedreiro", "Eletricista", "Pintura", "Limpeza"] },
  { value: "Imóveis", label: "Imóveis", subcategories: ["Vendas", "Locação de Temporada", "Administração"] },
  { value: "Tecnologia", label: "Tecnologia", subcategories: ["Desenvolvimento", "Suporte", "Marketing Digital"] },
  { value: "Educação", label: "Educação", subcategories: ["Ensino", "Instrução", "Coordenação"] },
];
